#!/bin/bash
# RStudio Server
wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.06.2-561-amd64.deb
sudo gdebi -n rstudio-server-2023.06.2-561-amd64.deb

# RStudio start
rstudio-server start
